import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        heading: ['Space Grotesk', 'Sora', 'sans-serif'],
        body: ['Inter', 'Manrope', 'sans-serif'],
        mono: ['JetBrains Mono', 'IBM Plex Mono', 'monospace'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // Pentagence semantic colors
        "pen-base": "hsl(var(--color-bg-base))",
        "pen-surface1": "hsl(var(--color-bg-surface-1))",
        "pen-surface2": "hsl(var(--color-bg-surface-2))",
        "pen-elevated": "hsl(var(--color-bg-elevated))",
        "pen-terminal": "hsl(var(--color-bg-terminal))",
        "pen-border-soft": "hsl(var(--color-border-soft))",
        "pen-border-strong": "hsl(var(--color-border-strong))",
        "pen-border-glow": "hsl(var(--color-border-glow))",
        "pen-text": "hsl(var(--color-text-primary))",
        "pen-text-secondary": "hsl(var(--color-text-secondary))",
        "pen-text-muted": "hsl(var(--color-text-muted))",
        "pen-text-terminal": "hsl(var(--color-text-terminal))",
        "pen-brand": "hsl(var(--color-brand-primary))",
        "pen-brand-hover": "hsl(var(--color-brand-primary-hover))",
        "pen-accent": "hsl(var(--color-brand-accent))",
        "pen-secondary": "hsl(var(--color-brand-secondary))",
        "pen-tertiary": "hsl(var(--color-brand-tertiary))",
        "pen-success": "hsl(var(--color-success))",
        "pen-success-muted": "hsl(var(--color-success-muted))",
        "pen-warning": "hsl(var(--color-warning))",
        "pen-warning-muted": "hsl(var(--color-warning-muted))",
        "pen-danger": "hsl(var(--color-danger))",
        "pen-danger-muted": "hsl(var(--color-danger-muted))",
        "pen-info": "hsl(var(--color-info))",
        "pen-info-muted": "hsl(var(--color-info-muted))",
        // Terminal-specific colors
        "terminal-green": "hsl(var(--color-terminal-green))",
        "terminal-cyan": "hsl(var(--color-terminal-cyan))",
        "terminal-magenta": "hsl(var(--color-terminal-magenta))",
        "terminal-yellow": "hsl(var(--color-terminal-yellow))",
        "terminal-orange": "hsl(var(--color-terminal-orange))",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "1.5rem",
      },
      boxShadow: {
        "pen-sm": "var(--shadow-sm)",
        "pen-md": "var(--shadow-md)",
        "pen-lg": "var(--shadow-lg)",
        "pen-glow-brand": "var(--shadow-glow-brand)",
        "pen-glow-accent": "var(--shadow-glow-accent)",
        "pen-glow-terminal": "var(--shadow-glow-terminal)",
        "pen-glow-danger": "var(--shadow-glow-danger)",
      },
      spacing: {
        "18": "4.5rem",
        "22": "5.5rem",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "grid-drift": {
          "0%, 100%": { transform: "translate(0, 0)" },
          "50%": { transform: "translate(-10px, -10px)" },
        },
        "scanline": {
          "0%": { transform: "translateY(-100%)", opacity: "0" },
          "10%": { opacity: "0.6" },
          "90%": { opacity: "0.6" },
          "100%": { transform: "translateY(100vh)", opacity: "0" },
        },
        "glow-pulse": {
          "0%, 100%": { opacity: "0.4" },
          "50%": { opacity: "0.8" },
        },
        "fade-in-up": {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "pulse-ring": {
          "0%": { transform: "scale(0.8)", opacity: "1" },
          "100%": { transform: "scale(1.4)", opacity: "0" },
        },
        "terminal-cursor-blink": {
          "0%, 50%": { opacity: "1" },
          "51%, 100%": { opacity: "0" },
        },
        "glitch": {
          "0%": { transform: "translate(0)" },
          "20%": { transform: "translate(-2px, 2px)" },
          "40%": { transform: "translate(-2px, -2px)" },
          "60%": { transform: "translate(2px, 2px)" },
          "80%": { transform: "translate(2px, -2px)" },
          "100%": { transform: "translate(0)" },
        },
        "matrix-rain": {
          "0%": { transform: "translateY(-100%)", opacity: "0" },
          "10%": { opacity: "1" },
          "90%": { opacity: "1" },
          "100%": { transform: "translateY(100vh)", opacity: "0" },
        },
        "border-glow": {
          "0%, 100%": { borderColor: "hsl(var(--color-brand-primary) / 0.3)", boxShadow: "0 0 5px hsl(var(--color-brand-primary) / 0.2)" },
          "50%": { borderColor: "hsl(var(--color-brand-primary) / 0.6)", boxShadow: "0 0 15px hsl(var(--color-brand-primary) / 0.4)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "shimmer": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "data-stream": {
          "0%": { backgroundPosition: "0% 0" },
          "100%": { backgroundPosition: "100% 100%" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "grid-drift": "grid-drift 20s ease-in-out infinite",
        "scanline": "scanline 10s linear infinite",
        "glow-pulse": "glow-pulse 4s ease-in-out infinite",
        "fade-in-up": "fade-in-up 0.5s ease-out",
        "pulse-ring": "pulse-ring 1.5s ease-out infinite",
        "terminal-cursor-blink": "terminal-cursor-blink 1s step-end infinite",
        "glitch": "glitch 0.3s cubic-bezier(.25, .46, .45, .94) both infinite",
        "matrix-rain": "matrix-rain 3s linear infinite",
        "border-glow": "border-glow 2s ease-in-out infinite",
        "float": "float 3s ease-in-out infinite",
        "shimmer": "shimmer 2s linear infinite",
        "data-stream": "data-stream 15s ease infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
